"""Constants used across the extraction modules."""

# Question detection constants
FOOTER_Y_CUTOFF = 750
X0_LEFT_COLUMN_MAX = 80
QNUM_CHAR_MARGIN = 1.0
TYPICAL_QNUM_X0 = 49.6
TOP_REGION_Y = 150

# Visual detection parameters (defaults)
DEFAULT_MIN_AREA = 5000
DEFAULT_MAX_AREA_RATIO = 0.70
DEFAULT_MIN_AREA_RATIO = 0.01
DEFAULT_MIN_ASPECT_RATIO = 0.2
DEFAULT_MAX_ASPECT_RATIO = 5.0
DEFAULT_MIN_EDGE_DENSITY = 0.01
DEFAULT_MERGE_HORIZONTAL_THRESHOLD = 200
DEFAULT_MERGE_VERTICAL_THRESHOLD = 100
DEFAULT_DPI = 300
